### ISSUE TITLE
gestion des valeurs négatives

### ISSUE THREAD

**Issue by larchuto** [robotronik/uart#2]
J'ai l'impression que les valeurs négatives ne sont pas gérée. Il faudrait donner du sens au caractère "-".

**Comment by robinmoussu** [comment]
C'est le cas.
Je vais essayer de fixer ça ce week-end.

On 24/04/2015 23:59, larchuto wrote:
>
> J'ai l'impression que les valeurs négatives ne sont pas gérée. Il
> faudrait donner du sens au caractère "-".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robotronik/uart/issues/2>.
>

-- 
Action Formation
/Robin Moussu
Délégué 2A filière SLE
École d’ingénieur ENSIMAG - Grenoble INP
/
/E-mail rédigé en  / /  / /  / /bépo <http://bepo.fr/wiki/Accueil> /

**Comment by larchuto** [comment]
l'uart a été déplacé dans common_code

Quoting Robin Moussu <notifications@github.com>:

**Comment by robinmoussu** [comment]
C'est plus haut niveau. C'est dans asser qu'il faut fixer ça. Le code
est prêt, mais il faut que j'arrive à le compiler. Le système de build
est tout cassé.

On 25/04/2015 14:02, larchuto wrote:
> l'uart a été déplacé dans common_code
>
> Quoting Robin Moussu <notifications@github.com>:
>
> > C'est le cas.
> > Je vais essayer de fixer ça ce week-end.
> >
> > On 24/04/2015 23:59, larchuto wrote:
> >>
> >> J'ai l'impression que les valeurs négatives ne sont pas gérée. Il
> >> faudrait donner du sens au caractère "-".
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/robotronik/uart/issues/2>.
> >>
> >
> > --
> > Action Formation
> > /Robin Moussu
> > Délégué 2A filière SLE
> > École d’ingénieur ENSIMAG - Grenoble INP
> > /
> > /E-mail rédigé en / / / / / /bépo <http://bepo.fr/wiki/Accueil> /
> >
> >
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/robotronik/uart/issues/2#issuecomment-96168615
>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robotronik/uart/issues/2#issuecomment-96188282>.
>

-- 
Action Formation
/Robin Moussu
Délégué 2A filière SLE
École d’ingénieur ENSIMAG - Grenoble INP
/
/E-mail rédigé en  / /  / /  / /bépo <http://bepo.fr/wiki/Accueil> /

**Comment by larchuto** [comment]
C'est tout cassé parce que ce code a été déplacé dans common_code.

Robin Moussu <notifications@github.com> a écrit :

**Comment by robinmoussu** [comment]
Non non, c'était le makefile qui n'étais plus bon. C'est fixé.
J'avais mis à jour common_code avant de râler ^^.

On 25/04/2015 15:55, larchuto wrote:
> C'est tout cassé parce que ce code a été déplacé dans common_code.
>
> Robin Moussu <notifications@github.com> a écrit :
>
> > C'est plus haut niveau. C'est dans asser qu'il faut fixer ça. Le code
> > est prêt, mais il faut que j'arrive à le compiler. Le système de build
> > est tout cassé.
> >
> > On 25/04/2015 14:02, larchuto wrote:
> >> l'uart a été déplacé dans common_code
> >>
> >> Quoting Robin Moussu <notifications@github.com>:
> >>
> >> > C'est le cas.
> >> > Je vais essayer de fixer ça ce week-end.
> >> >
> >> > On 24/04/2015 23:59, larchuto wrote:
> >> >>
> >> >> J'ai l'impression que les valeurs négatives ne sont pas gérée. Il
> >> >> faudrait donner du sens au caractère "-".
> >> >>
> >> >> —
> >> >> Reply to this email directly or view it on GitHub
> >> >> <https://github.com/robotronik/uart/issues/2>.
> >> >>
> >> >
> >> > --
> >> > Action Formation
> >> > /Robin Moussu
> >> > Délégué 2A filière SLE
> >> > École d’ingénieur ENSIMAG - Grenoble INP
> >> > /
> >> > /E-mail rédigé en / / / / / /bépo <http://bepo.fr/wiki/Accueil> /
> >> >
> >> >
> >> > ---
> >> > Reply to this email directly or view it on GitHub:
> >> > https://github.com/robotronik/uart/issues/2#issuecomment-96168615
> >>
> >>
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/robotronik/uart/issues/2#issuecomment-96188282>.
> >>
> >
> > --
> > Action Formation
> > /Robin Moussu
> > Délégué 2A filière SLE
> > École d’ingénieur ENSIMAG - Grenoble INP
> > /
> > /E-mail rédigé en / / / / / /bépo <http://bepo.fr/wiki/Accueil> /
> >
> >
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/robotronik/uart/issues/2#issuecomment-96189170
>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robotronik/uart/issues/2#issuecomment-96208052>.
>

-- 
Action Formation
/Robin Moussu
Délégué 2A filière SLE
École d’ingénieur ENSIMAG - Grenoble INP
/
/E-mail rédigé en  / /  / /  / /bépo <http://bepo.fr/wiki/Accueil> /
